In [3]:
import numpy as np

In [5]:
# cria uma matriz unidimensional
mt = np.array([12,34,26,18,10])
print(mt)
print(type(mt))

[12 34 26 18 10]
<class 'numpy.ndarray'>


In [13]:
# criar o array com um tipo específico
# cria o array como float de 64 bits
mtfloat = np.array([1,2,3], dtype= np.float64)
print(mtfloat)
print(type(mtfloat))
mtint = np.array([1,2,3], dtype = np.int32)
print(mtint)
print(type(mtint))

[1. 2. 3.]
<class 'numpy.ndarray'>
[1 2 3]
<class 'numpy.ndarray'>


In [23]:
# Mudar o tipo do array
# Podemos transformar o tipo de dados de arrays
mtnew = np.array([1.4, 3.6, -5.1, 9.42, 4.9999999])
print(mtnew)

# Quando transformamos de float para int os valores são truncados
mtnewint = mtnew.astype(np.int32)
print(mtnewint)

[ 1.4        3.6       -5.1        9.42       4.9999999]
[ 1  3 -5  9  4]


In [25]:
# podemos fazer o inverso também
mt5 = np.array([1,2,3,4])
print(mt5)
mt6 = mt5.astype(float)
print(mt6)

[1 2 3 4]
[1. 2. 3. 4.]


In [27]:
# mais de uma dimensão
# cria uma matriz bidemnsional
mt7 = np.array([[7,2,23],[12,27,4],[5,34,23]])
print(mt7)

[[ 7  2 23]
 [12 27  4]
 [ 5 34 23]]


In [33]:
# criar arrays vazios tipificados
# empty significa que não são inicializados, não que são vaios
vazio = np.empty([3,2], dtype = int)
print(vazio)
print("------------")

# Cria uma matriz 4x3 com valores zero
zeros = np.zeros([4,3])
print(zeros)
print("------------")

# Com valores iguais a um
um = np.ones([5,7])
print(um)

print("------------")

# Cria uma matriz quadrada com diagonal principal com valores 1 e os outros zero
diagonal = np.eye(5)
print(diagonal)


[[         782290819                  0]
 [388440235274403840        73059206828]
 [   284099207168000       511142855267]]
------------
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
------------
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
------------
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [43]:
# Valores aleatórios entre zero e um
ale = np.random.random((5))
print(ale)
print("------------")

# Valores aleatórios ditr. normal contendo negativo
ale2 = np.random.randn((5))
print(ale2)
print("------------")

# Valores aleatórios 3x4
ale3 = (10*np.random.random((3,4)))
print(ale3)


[0.4449916  0.6661773  0.60670768 0.01841367 0.50477553]
------------
[ 1.21602346  2.08797679 -1.98506215  0.72474941  1.28319471]
------------
[[9.08483808 2.3191801  5.78760377 1.60436569]
 [4.43326372 1.64167807 7.90643581 3.57685672]
 [0.92639928 6.6665306  7.80574199 6.41992114]]


In [65]:
# Outra forma de gerar aleatórios
# Uso de semente
gnr = np.random.default_rng(1)
ale5 = gnr.random(3)
print(ale5)

print("------------")

# Gerar inteiros
ale6 = gnr.integers(10, size=(3,4))
print(ale6)

[0.51182162 0.9504637  0.14415961]
------------
[[8 9 2 3]
 [8 4 2 8]
 [2 4 6 5]]


In [69]:
# Unique remove repetições
j = np.array([11,12, 12, 12,13,14,15,16,17,18,19,20])
j = np.unique(j)
print(j)

[11 12 13 14 15 16 17 18 19 20]


In [77]:
# Funções específicas
# Cria a matriz bidimensional k
k = np.array([[17,22,43],[27,25,14],[15,24,32]])

# Mostra a matriz k
print(k)

print("------------")

# Mostra um elemento específico da matriz k
print(k[0][1])

print("------------")

# Mostra o tamanho das dimensões da matriz k
print(k.shape)

[[17 22 43]
 [27 25 14]
 [15 24 32]]
------------
22
------------
(3, 3)


In [93]:
# Funções matemáticas
# Mostra o maior valor da matriz k
print(k.max())

print("------------")

# Mostra o menor valor da matriz k
print(k.min())

print("------------")

# Mostra a soma dos valores da matriz k
print((k.sum()))

print("------------")

# Mostra o valor da média dos valores da matriz k
print(k.mean())

print("------------")

# Mostra o valor do desvio padrão dos valores da matriz k
print(k.std())

43
------------
14
------------
219
------------
24.333333333333332
------------
8.615231988880057


In [101]:
# Funções universais, aplicadas a todos os elementos
# Mostra o valor da raiz quadrada de todos elementos
k1 = np.array([1,4,9,16,25,36])
print(np.sqrt(k1))

print("------------")

# Mostra o valor do exponencial de todos elementos
print(np.exp(k1))

[1. 2. 3. 4. 5. 6.]
------------
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10 4.31123155e+15]


In [109]:
# Extração de elementos
m = np.array([1,2,3,4,5,6])

# Mostra o elemento da posição 2
print(m[1])

print("------------")

# Mostra o array criado a partir da posição 0, dois elementos
print(m[0:2])

print("------------")

# Mostra o array criado a partir da 2a posição
# até todo o restante do array
print(m[1:])

print("------------")

# Mostra o array criado a partir da antepenúltima posição até a final
print(m[-3:])

2
------------
[1 2]
------------
[2 3 4 5 6]
------------
[4 5 6]


In [127]:
# Extração de linhas e colunas
l = np.array([[4,5],[6,1],[7,4]])
print(l)

print("------------")

# Primeira linha, todas as colunas
l_linha_1 = l[0,:]
print(l_linha_1)

print("------------")

# Segunda linha
l_linha_2 = l[1,:]
print(l_linha_2)

# Terceira linha
l_linha_3 = l[2,:]
print(l_linha_3)

print("------------")

# Todas as linhas, primeira coluna
l_coluna_1 = l[:,0]
print(l_coluna_1)

print("------------")

# Todas as linhas, segunda coluna
l_coluna_2 = l[:,1]
print(l_coluna_2)

[[4 5]
 [6 1]
 [7 4]]
------------
[4 5]
------------
[6 1]
[7 4]
------------
[4 6 7]
------------
[5 1 4]


In [9]:
# Adição e multiplicação de matrizes
n = np.array([[1,2],[3,4]])
o = np.array([[1,1],[1,1]])
res1 = n+o
print(res1)

print("------------")

res2 = n*o
print(res2)

print("------------")

p = np.array([[1,2],[3,4],[5,6]])
q = np.array([[2,1]])
print(q+p)

[[2 3]
 [4 5]]
------------
[[1 2]
 [3 4]]
------------
[[3 3]
 [5 5]
 [7 7]]


In [19]:
# Transposição, rearranja um conjunto de 15 elementos de 0 a 14
# em 3 linhas e 5 colunas
f = np.arange(15).reshape((3,5))
# Mostra a matriz transposta entre linha e coluna
print(f)
print("------------")
s = f.T
print(s)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
------------
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [23]:
# Outra forma de fazer, mesmo resultado
r = np.arange(15).reshape((3,5))
print(r)

print("------------")

# Rearranja um conjunto de 15 elementos
# Mostra a matriz transposta entre linha e coluna
s = r.transpose((1,0))
print(s)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
------------
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [27]:
# Expressões lógicas
# Usando where
# Criando matriz com valores aleatórios positivos e negativos
v = np.random.randn(4,4)
print(v)
print("------------")

# Criando matriz com valores booleanos baseado no array v
x = (v > 0)
print(x)
print("------------")

# Criando matriz com valores -1 e 1 baseado nos valores do array x 
z = np.where(x > 0, 1, -1)
print(z)

[[-0.57468486 -0.20247092 -0.41975733  0.34889318]
 [ 0.81301547 -0.30404609 -0.01352     0.44467343]
 [ 0.45403022  0.30677988 -0.16566935 -0.37938429]
 [-0.21439967 -0.0231714  -0.8309087   0.44007462]]
------------
[[False False False  True]
 [ True False False  True]
 [ True  True False False]
 [False False False  True]]
------------
[[-1 -1 -1  1]
 [ 1 -1 -1  1]
 [ 1  1 -1 -1]
 [-1 -1 -1  1]]
